<?php


namespace MinhNB\Jobs\Model\Attribute\Backend;

use Magento\Eav\Model\Entity\Attribute\Backend\AbstractBackend;

class Department extends AbstractBackend
{
    public function validate($object)
    {
        die;
        return parent::validate($object); // TODO: Change the autogenerated stub
    }
}