<?php


namespace MinhNB\Jobs\Model\Attribute\Frontend;

use Magento\Eav\Model\Entity\Attribute\Frontend\AbstractFrontend;

class Department extends AbstractFrontend
{
    public function getValue(\Magento\Framework\DataObject $object)
    {
        return parent::getValue($object); // TODO: Change the autogenerated stub
    }
}