<?php
use MinhNB\Jobs\Block\Adminhtml\Product\Attribute\Department;

/** @var Department $block */
?>
<div class="entry-edit form-inline">
    <fieldset class="fieldset admin__fieldset">
        <legend class="admin__legend legend">Attribute Department</legend>
        <br>
        <div class="admin__field field field-attribute_label">
            <label class="label admin__field-label">
                <span>Name</span>
            </label>
            <div class="admin__field-control control">
                <input id="department_name" name="department_name" type="text">
            </div>
        </div>
        <div class="admin__field field field-attribute_label">
            <label class="label admin__field-label">
                <span>Description</span>
            </label>
            <div class="admin__field-control control">
                <input id="department_description" name="department_description" type="text">
            </div>
        </div>
    </fieldset>
</div>

